# Encoder-Decoder(simple) Gru
## Developer: mehdi sahraei
### Importing

In [4]:
from numpy import array
from numpy import hstack
from keras.models import  Sequential
from keras.layers import GRU, Dropout, Dense, TimeDistributed, RepeatVector

### method

In [5]:
def split_sequence(sequence, n_step_in, n_step_out):
   x,y = list(), list() #x is data and y is label
   for i in range(len(sequence)):
       end_ix = i + n_step_in #timestep
       out_end_ix = end_ix + n_step_out # n-output
       if out_end_ix > len(sequence): #In this -if- we want if data be beyond len(sequence) , the command will not continue and break.
          break
       seq_x, seq_y = sequence[i:end_ix] , sequence[end_ix:out_end_ix]   
       x.append(seq_x)
       y.append(seq_y)
   return array(x) , array(y)

In [6]:
n_step_in, n_step_out = 3 , 2   
seq = [10,20,35,50,55,64,70,80,95]
      
x,y = split_sequence(seq, n_step_in, n_step_out)
print(x.shape,y.shape)   
   
for i in range(len(x)):
   print(x[i],y[i])

(5, 3) (5, 2)
[10 20 35] [50 55]
[20 35 50] [55 64]
[35 50 55] [64 70]
[50 55 64] [70 80]
[55 64 70] [80 95]


In [7]:
x.shape

(5, 3)

### training model

In [8]:
#The input must be three-dimensional or three-channel, that's why we reshape it
n_features = 1
x = x.reshape(x.shape[0],x.shape[1],n_features)    
y = y.reshape(y.shape[0],y.shape[1],n_features)

In [10]:
model = Sequential()

model.add(GRU(units=200, activation='tanh',  input_shape=(n_step_in,n_features))) # tanh is best activation in gru but relu also is used
model.add(RepeatVector(n_step_out))   
model.add(GRU(150,activation = 'tanh',return_sequences=True))   
model.add(TimeDistributed(Dense(1)))
model.compile(optimizer='RMSprop',loss='mse')   

In [13]:
model.fit(x,y,epochs=300,verbose=1)

Epoch 1/300
1/1 [==============================] - 0s 15ms/step - loss: 23.7128
Epoch 2/300
1/1 [==============================] - 0s 19ms/step - loss: 39.3419
Epoch 3/300
1/1 [==============================] - 0s 20ms/step - loss: 12.1494
Epoch 4/300
1/1 [==============================] - 0s 21ms/step - loss: 1.8917
Epoch 5/300
1/1 [==============================] - 0s 21ms/step - loss: 0.4039
Epoch 6/300
1/1 [==============================] - 0s 20ms/step - loss: 0.2632
Epoch 7/300
1/1 [==============================] - 0s 22ms/step - loss: 0.2069
Epoch 8/300
1/1 [==============================] - 0s 35ms/step - loss: 0.1677
Epoch 9/300
1/1 [==============================] - 0s 25ms/step - loss: 0.1375
Epoch 10/300
1/1 [==============================] - 0s 24ms/step - loss: 0.1135
Epoch 11/300
1/1 [==============================] - 0s 25ms/step - loss: 0.0942
Epoch 12/300
1/1 [==============================] - 0s 19ms/step - loss: 0.0784
Epoch 13/300
1/1 [============================

1/1 [==============================] - 0s 22ms/step - loss: 41.5464
Epoch 104/300
1/1 [==============================] - 0s 23ms/step - loss: 4.6154
Epoch 105/300
1/1 [==============================] - 0s 21ms/step - loss: 0.9175
Epoch 106/300
1/1 [==============================] - 0s 19ms/step - loss: 0.3418
Epoch 107/300
1/1 [==============================] - 0s 18ms/step - loss: 0.1926
Epoch 108/300
1/1 [==============================] - 0s 17ms/step - loss: 0.1074
Epoch 109/300
1/1 [==============================] - 0s 18ms/step - loss: 0.0714
Epoch 110/300
1/1 [==============================] - 0s 18ms/step - loss: 0.0517
Epoch 111/300
1/1 [==============================] - 0s 20ms/step - loss: 0.0421
Epoch 112/300
1/1 [==============================] - 0s 23ms/step - loss: 0.0376
Epoch 113/300
1/1 [==============================] - 0s 17ms/step - loss: 0.0379
Epoch 114/300
1/1 [==============================] - 0s 21ms/step - loss: 0.0441
Epoch 115/300
1/1 [======================

1/1 [==============================] - 0s 28ms/step - loss: 0.1194
Epoch 205/300
1/1 [==============================] - 0s 22ms/step - loss: 0.0923
Epoch 206/300
1/1 [==============================] - 0s 19ms/step - loss: 0.0720
Epoch 207/300
1/1 [==============================] - 0s 18ms/step - loss: 0.0564
Epoch 208/300
1/1 [==============================] - 0s 18ms/step - loss: 0.0444
Epoch 209/300
1/1 [==============================] - 0s 18ms/step - loss: 0.0350
Epoch 210/300
1/1 [==============================] - 0s 19ms/step - loss: 0.0277
Epoch 211/300
1/1 [==============================] - 0s 17ms/step - loss: 0.0220
Epoch 212/300
1/1 [==============================] - 0s 18ms/step - loss: 0.0175
Epoch 213/300
1/1 [==============================] - 0s 19ms/step - loss: 0.0140
Epoch 214/300
1/1 [==============================] - 0s 20ms/step - loss: 0.0113
Epoch 215/300
1/1 [==============================] - 0s 18ms/step - loss: 0.0091
Epoch 216/300
1/1 [=======================

### testing

In [14]:
x_input = array([10,20,35])
x_input = x_input.reshape(1, n_step_in, n_features)
x_input.shape

(1, 3, 1)

In [15]:
yhat = model.predict(x_input,verbose=0)
print('hat y:',yhat,'\n')
print('real y',y[0])

hat y: [[[50.006165]
  [55.015926]]] 

real y [[50]
 [55]]
