# Multiple-Input-Gru
## Developer: mehdi sahraei
### Importing

In [2]:
from numpy import array
from keras.models import Sequential
from keras.layers import GRU, Dense, Dropout        
from numpy import hstack

### method

In [3]:
def split_sequence(sequence, n_step):
   x,y = list(), list() #x is data and y is label
   for i in range(len(sequence)):
       end_ix = i + n_step
   
       if end_ix > len(sequence) - 1: # In this -if- we want if data be beyond len(sequence)-1, the command will not continue and break.
          break
       seq_x, seq_y = sequence[i:end_ix,:] , sequence[end_ix,:] # whole column
       x.append(seq_x)
       y.append(seq_y)
   return array(x) , array(y)

- making data x , y

In [4]:

seq1 = array([10,20,30,40,50,60,70,80,90])
seq2 = array([10,20,30,40,50,60,70,80,90])
seq3 = array([10,20,30,40,50,60,70,80,90])
   

seq1 = seq1.reshape((len(seq1),1)) #reshape: (9, 1)
seq2 = seq2.reshape((len(seq2),1)) #reshape: (9, 1)
seq3 = seq3.reshape((len(seq3),1)) #reshape: (9, 1)


dataset = hstack((seq1,seq2,seq3)) #function is used to stack the sequence of input arrays horizontally
dataset

array([[10, 10, 10],
       [20, 20, 20],
       [30, 30, 30],
       [40, 40, 40],
       [50, 50, 50],
       [60, 60, 60],
       [70, 70, 70],
       [80, 80, 80],
       [90, 90, 90]])

In [5]:
print('-'*75) #print -----


n_steps = 3 #timestep or look_up
x,y = split_sequence(dataset, n_steps)
print(x.shape,y.shape)   
   
for i in range(len(x)):
   print(x[i],y[i])
   

---------------------------------------------------------------------------
(6, 3, 3) (6, 3)
[[10 10 10]
 [20 20 20]
 [30 30 30]] [40 40 40]
[[20 20 20]
 [30 30 30]
 [40 40 40]] [50 50 50]
[[30 30 30]
 [40 40 40]
 [50 50 50]] [60 60 60]
[[40 40 40]
 [50 50 50]
 [60 60 60]] [70 70 70]
[[50 50 50]
 [60 60 60]
 [70 70 70]] [80 80 80]
[[60 60 60]
 [70 70 70]
 [80 80 80]] [90 90 90]


### training model

In [6]:
n_features = x.shape[2]
n_features

3

In [13]:
model = Sequential()

model.add(GRU(units=200, activation='tanh',  input_shape=(n_steps,n_features))) # tanh is best activation in gru but relu also is used

model.add(Dense(n_features)) #n-output  
   
model.compile(optimizer='RMSprop',loss='mse') #adam also is used

In [14]:
model.fit(x,y,epochs=800,verbose=1) #verbose is the choice that how you want to see the output of your Nural Network while it's training. If you set verbose = 0, It will show nothing

Epoch 1/800
1/1 [==============================] - 2s 2s/step - loss: 4513.0703
Epoch 2/800
1/1 [==============================] - 0s 15ms/step - loss: 4348.7588
Epoch 3/800
1/1 [==============================] - 0s 15ms/step - loss: 4241.4438
Epoch 4/800
1/1 [==============================] - 0s 15ms/step - loss: 4150.7856
Epoch 5/800
1/1 [==============================] - 0s 20ms/step - loss: 4072.0940
Epoch 6/800
1/1 [==============================] - 0s 17ms/step - loss: 4000.2874
Epoch 7/800
1/1 [==============================] - 0s 16ms/step - loss: 3931.2478
Epoch 8/800
1/1 [==============================] - 0s 19ms/step - loss: 3863.6213
Epoch 9/800
1/1 [==============================] - 0s 15ms/step - loss: 3794.2568
Epoch 10/800
1/1 [==============================] - 0s 16ms/step - loss: 3727.1230
Epoch 11/800
1/1 [==============================] - 0s 14ms/step - loss: 3660.0801
Epoch 12/800
1/1 [==============================] - 0s 23ms/step - loss: 3594.3174
Epoch 13/800
1/

1/1 [==============================] - 0s 15ms/step - loss: 628.9104
Epoch 198/800
1/1 [==============================] - 0s 16ms/step - loss: 622.2100
Epoch 199/800
1/1 [==============================] - 0s 14ms/step - loss: 615.5352
Epoch 200/800
1/1 [==============================] - 0s 14ms/step - loss: 608.9330
Epoch 201/800
1/1 [==============================] - 0s 13ms/step - loss: 602.3521
Epoch 202/800
1/1 [==============================] - 0s 14ms/step - loss: 595.7959
Epoch 203/800
1/1 [==============================] - 0s 15ms/step - loss: 589.3146
Epoch 204/800
1/1 [==============================] - 0s 15ms/step - loss: 582.8752
Epoch 205/800
1/1 [==============================] - 0s 16ms/step - loss: 576.4839
Epoch 206/800
1/1 [==============================] - 0s 13ms/step - loss: 569.8610
Epoch 207/800
1/1 [==============================] - 0s 15ms/step - loss: 563.3276
Epoch 208/800
1/1 [==============================] - 0s 18ms/step - loss: 556.7571
Epoch 209/800
1/1 

1/1 [==============================] - 0s 14ms/step - loss: 16.1167
Epoch 395/800
1/1 [==============================] - 0s 17ms/step - loss: 16.0408
Epoch 396/800
1/1 [==============================] - 0s 17ms/step - loss: 15.4242
Epoch 397/800
1/1 [==============================] - 0s 16ms/step - loss: 15.6348
Epoch 398/800
1/1 [==============================] - 0s 16ms/step - loss: 14.8612
Epoch 399/800
1/1 [==============================] - 0s 15ms/step - loss: 15.0784
Epoch 400/800
1/1 [==============================] - 0s 15ms/step - loss: 14.4166
Epoch 401/800
1/1 [==============================] - 0s 17ms/step - loss: 14.8433
Epoch 402/800
1/1 [==============================] - 0s 15ms/step - loss: 13.8357
Epoch 403/800
1/1 [==============================] - 0s 16ms/step - loss: 14.0580
Epoch 404/800
1/1 [==============================] - 0s 14ms/step - loss: 12.9022
Epoch 405/800
1/1 [==============================] - 0s 15ms/step - loss: 12.9367
Epoch 406/800
1/1 [===========

Epoch 495/800
1/1 [==============================] - 0s 17ms/step - loss: 10.3920
Epoch 496/800
1/1 [==============================] - 0s 17ms/step - loss: 7.6219
Epoch 497/800
1/1 [==============================] - 0s 15ms/step - loss: 5.8966
Epoch 498/800
1/1 [==============================] - 0s 13ms/step - loss: 1.9495
Epoch 499/800
1/1 [==============================] - 0s 15ms/step - loss: 1.2442
Epoch 500/800
1/1 [==============================] - 0s 17ms/step - loss: 0.7888
Epoch 501/800
1/1 [==============================] - 0s 15ms/step - loss: 0.6680
Epoch 502/800
1/1 [==============================] - 0s 16ms/step - loss: 0.5920
Epoch 503/800
1/1 [==============================] - 0s 16ms/step - loss: 0.5678
Epoch 504/800
1/1 [==============================] - 0s 15ms/step - loss: 0.5691
Epoch 505/800
1/1 [==============================] - 0s 17ms/step - loss: 0.6403
Epoch 506/800
1/1 [==============================] - 0s 17ms/step - loss: 0.8363
Epoch 507/800
1/1 [========

1/1 [==============================] - 0s 16ms/step - loss: 0.0329
Epoch 597/800
1/1 [==============================] - 0s 15ms/step - loss: 0.0288
Epoch 598/800
1/1 [==============================] - 0s 16ms/step - loss: 0.0260
Epoch 599/800
1/1 [==============================] - 0s 15ms/step - loss: 0.0239
Epoch 600/800
1/1 [==============================] - 0s 16ms/step - loss: 0.0221
Epoch 601/800
1/1 [==============================] - 0s 16ms/step - loss: 0.0206
Epoch 602/800
1/1 [==============================] - 0s 15ms/step - loss: 0.0192
Epoch 603/800
1/1 [==============================] - 0s 14ms/step - loss: 0.0180
Epoch 604/800
1/1 [==============================] - 0s 15ms/step - loss: 0.0170
Epoch 605/800
1/1 [==============================] - 0s 15ms/step - loss: 0.0160
Epoch 606/800
1/1 [==============================] - 0s 15ms/step - loss: 0.0151
Epoch 607/800
1/1 [==============================] - 0s 15ms/step - loss: 0.0145
Epoch 608/800
1/1 [=======================

1/1 [==============================] - 0s 15ms/step - loss: 0.1388
Epoch 799/800
1/1 [==============================] - 0s 18ms/step - loss: 0.2932
Epoch 800/800
1/1 [==============================] - 0s 16ms/step - loss: 0.8460


### testing

In [15]:
x_input = array([[10,10,10],[20,20,20],[30,30,30]])
x_input

array([[10, 10, 10],
       [20, 20, 20],
       [30, 30, 30]])

In [16]:
x_input = x_input.reshape(1, n_steps, n_features)

yhat = model.predict(x_input,verbose=0) 
print(yhat)

[[40.29965  40.353172 40.253757]]
