# Simple Gru

## Developer: mehdi sahraei

### Importing

In [97]:
from numpy import array
from keras.models import Sequential
from keras.layers import GRU, Dense, Dropout

### method

In [98]:
def split_sequence(sequence, n_step):
   x,y = list(), list() #x is data and y is label
   for i in range(len(sequence)):
       end_ix = i + n_step
   
       if end_ix > len(sequence) - 1: # In this -if- we want if data be beyond len(sequence)-1, the command will not continue and break..
          break
       seq_x, seq_y = sequence[i:end_ix] , sequence[end_ix]   
       x.append(seq_x)
       y.append(seq_y)
   return array(x) , array(y)

- making data x , y

In [99]:
n_steps = 3 #timestep or look_up
seq_value = [10,20,30,40,50,60,70,80,90]
   
x,y = split_sequence(seq_value , n_steps)

for i in range(len(x)):   
   print(x[i],y[i])

[10 20 30] 40
[20 30 40] 50
[30 40 50] 60
[40 50 60] 70
[50 60 70] 80
[60 70 80] 90


In [100]:
print(x.shape)
print(y.shape)

(6, 3)
(6,)


### training model

In [101]:
#The input must be three-dimensional or three-channel, that's why we reshape it
n_features = 1 
x = x.reshape(x.shape[0],x.shape[1],n_features) 
x.shape

(6, 3, 1)

In [ ]:
model = Sequential()

model.add(GRU(units=100, activation='tanh',  input_shape=(n_steps,n_features))) # tanh is best activation in gru but relu also is used

model.add(Dense(1)) #n-output  
   
model.compile(optimizer='RMSprop',loss='mse') #adam also is used

In [93]:
model.fit(x,y,epochs=800,verbose=1) #verbose is the choice that how you want to see the output of your Nural Network while it's training. If you set verbose = 0, It will show nothing

Epoch 1/800
1/1 [==============================] - 0s 11ms/step - loss: 505.6681
Epoch 2/800
1/1 [==============================] - 0s 12ms/step - loss: 502.4999
Epoch 3/800
1/1 [==============================] - 0s 11ms/step - loss: 499.2821
Epoch 4/800
1/1 [==============================] - 0s 11ms/step - loss: 496.0250
Epoch 5/800
1/1 [==============================] - 0s 11ms/step - loss: 492.7292
Epoch 6/800
1/1 [==============================] - 0s 13ms/step - loss: 489.4154
Epoch 7/800
1/1 [==============================] - 0s 14ms/step - loss: 486.0912
Epoch 8/800
1/1 [==============================] - 0s 14ms/step - loss: 482.7589
Epoch 9/800
1/1 [==============================] - 0s 12ms/step - loss: 479.4174
Epoch 10/800
1/1 [==============================] - 0s 12ms/step - loss: 476.0562
Epoch 11/800
1/1 [==============================] - 0s 17ms/step - loss: 472.6678
Epoch 12/800
1/1 [==============================] - 0s 19ms/step - loss: 469.2468
Epoch 13/800
1/1 [=======

1/1 [==============================] - 0s 10ms/step - loss: 233.9481
Epoch 102/800
1/1 [==============================] - 0s 10ms/step - loss: 231.9845
Epoch 103/800
1/1 [==============================] - 0s 11ms/step - loss: 230.0864
Epoch 104/800
1/1 [==============================] - 0s 12ms/step - loss: 228.1480
Epoch 105/800
1/1 [==============================] - 0s 12ms/step - loss: 226.2734
Epoch 106/800
1/1 [==============================] - 0s 12ms/step - loss: 224.3602
Epoch 107/800
1/1 [==============================] - 0s 11ms/step - loss: 222.5091
Epoch 108/800
1/1 [==============================] - 0s 12ms/step - loss: 220.6204
Epoch 109/800
1/1 [==============================] - 0s 16ms/step - loss: 218.7932
Epoch 110/800
1/1 [==============================] - 0s 13ms/step - loss: 216.9283
Epoch 111/800
1/1 [==============================] - 0s 12ms/step - loss: 215.1248
Epoch 112/800
1/1 [==============================] - 0s 18ms/step - loss: 213.2828
Epoch 113/800
1/1 

Epoch 200/800
1/1 [==============================] - 0s 13ms/step - loss: 90.0860
Epoch 201/800
1/1 [==============================] - 0s 13ms/step - loss: 89.1161
Epoch 202/800
1/1 [==============================] - 0s 10ms/step - loss: 88.0972
Epoch 203/800
1/1 [==============================] - 0s 11ms/step - loss: 87.1439
Epoch 204/800
1/1 [==============================] - 0s 12ms/step - loss: 86.1432
Epoch 205/800
1/1 [==============================] - 0s 12ms/step - loss: 85.2065
Epoch 206/800
1/1 [==============================] - 0s 12ms/step - loss: 84.2233
Epoch 207/800
1/1 [==============================] - 0s 13ms/step - loss: 83.3033
Epoch 208/800
1/1 [==============================] - 0s 15ms/step - loss: 82.3371
Epoch 209/800
1/1 [==============================] - 0s 14ms/step - loss: 81.4339
Epoch 210/800
1/1 [==============================] - 0s 12ms/step - loss: 80.4843
Epoch 211/800
1/1 [==============================] - 0s 12ms/step - loss: 79.5984
Epoch 212/800
1/

Epoch 300/800
1/1 [==============================] - 0s 13ms/step - loss: 22.9983
Epoch 301/800
1/1 [==============================] - 0s 11ms/step - loss: 22.6307
Epoch 302/800
1/1 [==============================] - 0s 14ms/step - loss: 22.2333
Epoch 303/800
1/1 [==============================] - 0s 11ms/step - loss: 21.8872
Epoch 304/800
1/1 [==============================] - 0s 11ms/step - loss: 21.5188
Epoch 305/800
1/1 [==============================] - 0s 10ms/step - loss: 21.1908
Epoch 306/800
1/1 [==============================] - 0s 10ms/step - loss: 20.8411
Epoch 307/800
1/1 [==============================] - 0s 11ms/step - loss: 20.5208
Epoch 308/800
1/1 [==============================] - 0s 12ms/step - loss: 20.1764
Epoch 309/800
1/1 [==============================] - 0s 12ms/step - loss: 19.8544
Epoch 310/800
1/1 [==============================] - 0s 13ms/step - loss: 19.5108
Epoch 311/800
1/1 [==============================] - 0s 14ms/step - loss: 19.1886
Epoch 312/800
1/

1/1 [==============================] - 0s 12ms/step - loss: 3.4377
Epoch 401/800
1/1 [==============================] - 0s 13ms/step - loss: 3.4619
Epoch 402/800
1/1 [==============================] - 0s 14ms/step - loss: 3.4380
Epoch 403/800
1/1 [==============================] - 0s 10ms/step - loss: 3.5130
Epoch 404/800
1/1 [==============================] - 0s 12ms/step - loss: 3.4990
Epoch 405/800
1/1 [==============================] - 0s 12ms/step - loss: 3.5672
Epoch 406/800
1/1 [==============================] - 0s 11ms/step - loss: 3.4781
Epoch 407/800
1/1 [==============================] - 0s 11ms/step - loss: 3.4300
Epoch 408/800
1/1 [==============================] - 0s 11ms/step - loss: 3.1948
Epoch 409/800
1/1 [==============================] - 0s 11ms/step - loss: 3.0018
Epoch 410/800
1/1 [==============================] - 0s 13ms/step - loss: 2.7361
Epoch 411/800
1/1 [==============================] - 0s 12ms/step - loss: 2.5986
Epoch 412/800
1/1 [=======================

1/1 [==============================] - 0s 11ms/step - loss: 0.6843
Epoch 502/800
1/1 [==============================] - 0s 13ms/step - loss: 0.5222
Epoch 503/800
1/1 [==============================] - 0s 13ms/step - loss: 0.4574
Epoch 504/800
1/1 [==============================] - 0s 11ms/step - loss: 0.4426
Epoch 505/800
1/1 [==============================] - 0s 12ms/step - loss: 0.4766
Epoch 506/800
1/1 [==============================] - 0s 10ms/step - loss: 0.5637
Epoch 507/800
1/1 [==============================] - 0s 11ms/step - loss: 0.6999
Epoch 508/800
1/1 [==============================] - 0s 12ms/step - loss: 0.8941
Epoch 509/800
1/1 [==============================] - 0s 12ms/step - loss: 1.0957
Epoch 510/800
1/1 [==============================] - 0s 13ms/step - loss: 1.2375
Epoch 511/800
1/1 [==============================] - 0s 15ms/step - loss: 1.2911
Epoch 512/800
1/1 [==============================] - 0s 14ms/step - loss: 1.2105
Epoch 513/800
1/1 [=======================

1/1 [==============================] - 0s 12ms/step - loss: 0.4076
Epoch 603/800
1/1 [==============================] - 0s 15ms/step - loss: 0.6545
Epoch 604/800
1/1 [==============================] - 0s 14ms/step - loss: 0.9788
Epoch 605/800
1/1 [==============================] - 0s 16ms/step - loss: 1.3493
Epoch 606/800
1/1 [==============================] - 0s 11ms/step - loss: 1.3994
Epoch 607/800
1/1 [==============================] - 0s 13ms/step - loss: 1.2928
Epoch 608/800
1/1 [==============================] - 0s 12ms/step - loss: 0.9303
Epoch 609/800
1/1 [==============================] - 0s 11ms/step - loss: 0.7101
Epoch 610/800
1/1 [==============================] - 0s 11ms/step - loss: 0.5099
Epoch 611/800
1/1 [==============================] - 0s 12ms/step - loss: 0.4256
Epoch 612/800
1/1 [==============================] - 0s 15ms/step - loss: 0.3720
Epoch 613/800
1/1 [==============================] - 0s 14ms/step - loss: 0.3794
Epoch 614/800
1/1 [=======================

1/1 [==============================] - 0s 17ms/step - loss: 1.1570
Epoch 704/800
1/1 [==============================] - 0s 13ms/step - loss: 1.2035
Epoch 705/800
1/1 [==============================] - 0s 16ms/step - loss: 1.1805
Epoch 706/800
1/1 [==============================] - 0s 12ms/step - loss: 0.9076
Epoch 707/800
1/1 [==============================] - 0s 13ms/step - loss: 0.7296
Epoch 708/800
1/1 [==============================] - 0s 14ms/step - loss: 0.5272
Epoch 709/800
1/1 [==============================] - 0s 14ms/step - loss: 0.4259
Epoch 710/800
1/1 [==============================] - 0s 14ms/step - loss: 0.3507
Epoch 711/800
1/1 [==============================] - 0s 14ms/step - loss: 0.3398
Epoch 712/800
1/1 [==============================] - 0s 11ms/step - loss: 0.3483
Epoch 713/800
1/1 [==============================] - 0s 14ms/step - loss: 0.4100
Epoch 714/800
1/1 [==============================] - 0s 13ms/step - loss: 0.4955
Epoch 715/800
1/1 [=======================

### testing

In [94]:
x_input = array([20,30,40])
x_input = x_input.reshape(1,n_steps,n_features)

In [95]:
x_input.shape

(1, 3, 1)

In [96]:
yhat = model.predict(x_input, verbose=0)
print('predicted:',yhat)
print('real:',y[1])

predicted: [[50.979904]]
real: 50
